import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";

import { 
    faWaze,
    faTiktok,
    faInstagram,
    faYoutube
} from "@fortawesome/free-brands-svg-icons";

import { 
    faEarthEurope, 
    faAngleLeft, 
    faFontAwesome, 
    faMagnifyingGlass, 
    faXmark, 
    faUser, 
    faUsers, 
    faGear,
    faGavel,
    faWrench,
    faMobileButton,
    faRightFromBracket,
    faHeart,
    faMapLocationDot, 
    faLink,
    faUserPlus,
    faLock,
    faLockOpen,
    faEye,
    faEyeSlash,
    faTrash,
    faArrowUpRightFromSquare,
    faShare,
    faRotateRight,
    faPlus,
    faCircleCheck,
    faChessRook,
    faHotel,
    faFilm,
    faTrain,
    faHospital,
    faHouse,
    faIndustry,
    faBuilding,
    faUtensils,
    faJetFighterUp,
    faMapPin,
    faTriangleExclamation
    
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faEarthEurope, 
    faWaze, 
    faAngleLeft, 
    faFontAwesome, 
    faMagnifyingGlass, 
    faXmark, 
    faUser,
    faGear,
    faMobileButton,
    faRightFromBracket,
    faHeart,
    faUsers,
    faMapLocationDot,
    faLink,
    faUserPlus,
    faLock,
    faLockOpen,
    faEye,
    faEyeSlash,
    faTrash,
    faArrowUpRightFromSquare,
    faTiktok,
    faInstagram,
    faYoutube,
    faShare,
    faRotateRight,
    faPlus,
    faCircleCheck,
    faChessRook,
    faHotel,
    faFilm,
    faTrain,
    faHospital,
    faHouse,
    faIndustry,
    faBuilding,
    faUtensils,
    faJetFighterUp,
    faMapPin,
    faGavel,
    faWrench,
    faTriangleExclamation
);

export default FontAwesomeIcon;